INFO:__main__:Current ip - 192.168.8.186
WARNING:db:Connecting to MariaDB Platform
ERROR:db:MariaDB -Error connecting to MariaDB Platform: Can't connect to server on '127.0.0.1' (10061)
INFO:db:Checking if tables exist inside the db
INFO:__main__:Current ip - 192.168.8.186
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.8.186:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug: * Restarting with stat
INFO:__main__:Current ip - 192.168.8.186
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 197-790-057
INFO:__main__:Welcome to SovietWave Radio currently its in night mode
INFO:werkzeug:127.0.0.1 - - [15/Apr/2023 23:40:19] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Apr/2023 23:40:20] "GET /static/styles/style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Apr/2023 23:40:20] "GET /static/js/radio.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Apr/2023 23:40:20] "GET /static/play.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Apr/2023 23:40:22] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
WARNING:__main__:Trying to get /track_name
WARNING:__main__:127.0.0.1 accessing /get_songs_data
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8000
INFO:werkzeug:127.0.0.1 - - [15/Apr/2023 23:40:25] "[35m[1mGET /get_songs_data?title=Connecting... HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [15/Apr/2023 23:40:29] "[35m[1mGET /track_name HTTP/1.1[0m" 500 -
WARNING:__main__:Trying to get /track_name
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8000
WARNING:__main__:127.0.0.1 accessing /get_songs_data
INFO:werkzeug:127.0.0.1 - - [15/Apr/2023 23:40:30] "[35m[1mGET /get_songs_data?title=Connecting... HTTP/1.1[0m" 500 -
INFO:__main__:Current ip - 192.168.8.186
INFO:__main__:Current ip - 192.168.8.186
INFO:__main__:Current ip - 192.168.8.186
INFO:__main__:Current ip - 192.168.8.186
INFO:__main__:Current ip - 192.168.8.186
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.8.186:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
WARNING:__main__:Trying to get /track_name
WARNING:__main__:127.0.0.1 accessing /get_songs_data
INFO:werkzeug:127.0.0.1 - - [15/Apr/2023 23:57:08] "[31m[1mGET /get_songs_data?title=Connecting... HTTP/1.1[0m" 400 -
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8000
WARNING:__main__:127.0.0.1 accessing /get_songs_data
INFO:werkzeug:127.0.0.1 - - [15/Apr/2023 23:57:10] "[31m[1mGET /get_songs_data?title=Connecting... HTTP/1.1[0m" 400 -
INFO:__main__:Welcome to SovietWave Radio currently its in night mode
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\714h\Desktop\WebRadioTemplate-main\app.py", line 108, in home
    if not mt.maintance:
NameError: name 'mt' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Apr/2023 23:57:10] "[35m[1mGET / HTTP/1.1[0m" 500 -
ERROR:app:Exception on /track_name [GET]
Traceback (most recent call last):
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\urllib3\connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000018EB4D2F580>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /status.xsl (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018EB4D2F580>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\714h\Desktop\WebRadioTemplate-main\app.py", line 118, in track_name
    response = requests.get(status_url)
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /status.xsl (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018EB4D2F580>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
INFO:werkzeug:127.0.0.1 - - [15/Apr/2023 23:57:12] "[35m[1mGET /track_name HTTP/1.1[0m" 500 -
INFO:__main__:Welcome to SovietWave Radio currently its in night mode
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\714h\Desktop\WebRadioTemplate-main\app.py", line 108, in home
    if not mt.maintance:
NameError: name 'mt' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Apr/2023 23:57:24] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:__main__:Welcome to SovietWave Radio currently its in night mode
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\714h\Desktop\WebRadioTemplate-main\app.py", line 108, in home
    if not mt.maintance:
NameError: name 'mt' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Apr/2023 23:57:25] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:__main__:Welcome to SovietWave Radio currently its in night mode
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\714h\Desktop\WebRadioTemplate-main\app.py", line 108, in home
    if not mt.maintance:
NameError: name 'mt' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Apr/2023 23:57:26] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:__main__:Welcome to SovietWave Radio currently its in night mode
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\714h\Desktop\WebRadioTemplate-main\app.py", line 108, in home
    if not mt.maintance:
NameError: name 'mt' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Apr/2023 23:57:26] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:__main__:Welcome to SovietWave Radio currently its in night mode
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\714h\Desktop\WebRadioTemplate-main\app.py", line 108, in home
    if not mt.maintance:
NameError: name 'mt' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Apr/2023 23:57:27] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:__main__:Welcome to SovietWave Radio currently its in night mode
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\714h\Desktop\WebRadioTemplate-main\app.py", line 108, in home
    if not mt.maintance:
NameError: name 'mt' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Apr/2023 23:57:27] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:__main__:Welcome to SovietWave Radio currently its in night mode
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\714h\Desktop\WebRadioTemplate-main\app.py", line 108, in home
    if not mt.maintance:
NameError: name 'mt' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Apr/2023 23:57:28] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:__main__:Welcome to SovietWave Radio currently its in night mode
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\714h\Desktop\WebRadioTemplate-main\app.py", line 108, in home
    if not mt.maintance:
NameError: name 'mt' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Apr/2023 23:57:28] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:__main__:Welcome to SovietWave Radio currently its in night mode
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\714h\Desktop\WebRadioTemplate-main\app.py", line 108, in home
    logger.info('Return of track name is successful.')
NameError: name 'mt' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Apr/2023 23:58:05] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:__main__:Welcome to SovietWave Radio currently its in night mode
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\714h\Desktop\WebRadioTemplate-main\app.py", line 108, in home
    logger.info('Return of track name is successful.')
NameError: name 'mt' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Apr/2023 23:58:06] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:__main__:Welcome to SovietWave Radio currently its in night mode
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\714h\Desktop\WebRadioTemplate-main\app.py", line 108, in home
    logger.info('Return of track name is successful.')
NameError: name 'mt' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Apr/2023 23:58:07] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:__main__:Welcome to SovietWave Radio currently its in night mode
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\714h\Desktop\WebRadioTemplate-main\app.py", line 108, in home
    logger.info('Return of track name is successful.')
NameError: name 'mt' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Apr/2023 23:58:07] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:__main__:Welcome to SovietWave Radio currently its in night mode
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\714h\Desktop\WebRadioTemplate-main\app.py", line 108, in home
    if not mt.maintance:
NameError: name 'mt' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Apr/2023 23:59:41] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:__main__:Welcome to SovietWave Radio currently its in night mode
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\714h\anaconda3\anaconda4\envs\py10\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\714h\Desktop\WebRadioTemplate-main\app.py", line 108, in home
    if not mt.maintance:
NameError: name 'mt' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Apr/2023 23:59:43] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:__main__:Current ip - 192.168.8.186
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.8.186:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug: * Restarting with stat
INFO:__main__:Current ip - 192.168.8.186
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 197-790-057
INFO:__main__:Welcome to SovietWave Radio currently its in night mode
INFO:werkzeug:127.0.0.1 - - [16/Apr/2023 00:00:16] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [16/Apr/2023 00:00:17] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Apr/2023 00:00:17] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Apr/2023 00:00:17] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Apr/2023 00:00:17] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
INFO:werkzeug: * Detected change in 'C:\\Users\\714h\\Desktop\\WebRadioTemplate-main\\app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:__main__:Current ip - 192.168.8.186
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 197-790-057
INFO:__main__:Welcome to SovietWave Radio currently its in night mode
INFO:werkzeug:127.0.0.1 - - [16/Apr/2023 00:00:51] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Apr/2023 00:00:51] "[36mGET /static/styles/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [16/Apr/2023 00:00:51] "[36mGET /static/js/radio.js HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [16/Apr/2023 00:00:51] "[36mGET /static/play.png HTTP/1.1[0m" 304 -
WARNING:__main__:Trying to get /track_name
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8000
WARNING:__main__:127.0.0.1 accessing /get_songs_data
INFO:werkzeug:127.0.0.1 - - [16/Apr/2023 00:00:57] "[35m[1mGET /get_songs_data?title=Connecting...%3Cdiv%20id%3D%22extwaiokist%22%20style%3D%22display%3Anone%22%20v%3D%22kmiah%22%20q%3D%22454e5eae%22%20c%3D%22932.1%22%20i%3D%22938%22%20u%3D%221.582%22%20s%3D%2204072304%22%20sg%3D%22svr_03162317-ga_04072304-bai_04042310%22%20d%3D%221%22%20w%3D%22false%22%20e%3D%22%22%20a%3D%222%22%20m%3D%22BMe%3D%22%3E%3Cdiv%20id%3D%22extwaigglbit%22%20style%3D%22display%3Anone%22%20v%3D%22kmiah%22%20q%3D%22454e5eae%22%20c%3D%22932.1%22%20i%3D%22938%22%20u%3D%221.582%22%20s%3D%2204072304%22%20sg%3D%22svr_03162317-ga_04072304-bai_04042310%22%20d%3D%221%22%20w%3D%22false%22%20e%3D%22%22%20a%3D%222%22%20m%3D%22BMe%3D%22%3E%3C%2Fdiv%3E%3C%2Fdiv%3E HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [16/Apr/2023 00:01:00] "[35m[1mGET /track_name HTTP/1.1[0m" 500 -
WARNING:__main__:Trying to get /track_name
WARNING:__main__:127.0.0.1 accessing /get_songs_data
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8000
INFO:werkzeug:127.0.0.1 - - [16/Apr/2023 00:01:02] "[35m[1mGET /get_songs_data?title=Connecting...%3Cdiv%20id%3D%22extwaiokist%22%20style%3D%22display%3Anone%22%20v%3D%22kmiah%22%20q%3D%22454e5eae%22%20c%3D%22932.1%22%20i%3D%22938%22%20u%3D%221.582%22%20s%3D%2204072304%22%20sg%3D%22svr_03162317-ga_04072304-bai_04042310%22%20d%3D%221%22%20w%3D%22false%22%20e%3D%22%22%20a%3D%222%22%20m%3D%22BMe%3D%22%3E%3Cdiv%20id%3D%22extwaigglbit%22%20style%3D%22display%3Anone%22%20v%3D%22kmiah%22%20q%3D%22454e5eae%22%20c%3D%22932.1%22%20i%3D%22938%22%20u%3D%221.582%22%20s%3D%2204072304%22%20sg%3D%22svr_03162317-ga_04072304-bai_04042310%22%20d%3D%221%22%20w%3D%22false%22%20e%3D%22%22%20a%3D%222%22%20m%3D%22BMe%3D%22%3E%3C%2Fdiv%3E%3C%2Fdiv%3E HTTP/1.1[0m" 500 -
